PROFILE_NAMES = Default DEVICE_duzun-dm06 DEVICE_gl-mt300n-v2 DEVICE_mt7628 DEVICE_mac1200r-v2 DEVICE_vocore2 DEVICE_wrtnode2p DEVICE_wl-wn575a3 DEVICE_miwifi-nano
Default_NAME:=Default Profile
Default_PACKAGES:=kmod-usb-core kmod-usb2 kmod-usb-ohci kmod-usb-ledtrig-usbport
DEVICE_duzun-dm06_NAME:=DuZun DM06
DEVICE_duzun-dm06_PACKAGES:=kmod-usb2 kmod-usb-ohci kmod-usb-ledtrig-usbport
DEVICE_gl-mt300n-v2_NAME:=GL-iNet GL-MT300N-V2
DEVICE_gl-mt300n-v2_PACKAGES:=kmod-usb2 kmod-usb-ohci kmod-usb-ledtrig-usbport
DEVICE_mt7628_NAME:=MediaTek MT7628 EVB
DEVICE_mt7628_PACKAGES:=kmod-usb2 kmod-usb-ohci kmod-usb-ledtrig-usbport
DEVICE_mac1200r-v2_NAME:=Mercury MAC1200R v2.0
DEVICE_mac1200r-v2_PACKAGES:=
DEVICE_vocore2_NAME:=VoCore VoCore2
DEVICE_vocore2_PACKAGES:=kmod-usb2 kmod-usb-ohci kmod-usb-ledtrig-usbport kmod-sdhci kmod-sdhci-mt7620
DEVICE_wrtnode2p_NAME:=WRTnode 2P
DEVICE_wrtnode2p_PACKAGES:=kmod-usb2 kmod-usb-ohci kmod-usb-ledtrig-usbport
DEVICE_wl-wn575a3_NAME:=Wavlink WL-WN575A3
DEVICE_wl-wn575a3_PACKAGES:=
DEVICE_miwifi-nano_NAME:=Xiaomi MiWiFi Nano
DEVICE_miwifi-nano_PACKAGES:=kmod-usb2 kmod-usb-ohci kmod-usb-ledtrig-usbport
